### ISSUE TITLE
Vertica ODBC Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by masoudganji** [DeBoerTool/laravel-odbc-driver#10]
Hi
In Laravel 7 I have this:
Segmentation fault (core dumped)

**Comment by danielsdeboer** [comment]
Probably not an issue with this package, but either way that's not really enough information to debug anything.

**Comment by masoudganji** [comment]
Thanks for your answer. I have this problem when I use libverticaodbc.so as an ODBC file (it is for Vertica 9.2). I checked your ODBC package with a mysql ODBC and it works fine without any errors.
I guess this problem is from php7.4 or Vertica ODBC file. It is a bad error because I cannot connect to my database with Lavravel.

**Comment by danielsdeboer** [comment]
Yeah if you're getting a segfault I'd try some other kind of ODBC connection method first (get PHP & Laravel out of loop), see if you can replicate the segfault that way. If that works then start adding stuff in and find what layer (PHP, PDO, Laravel) the problem reemerges at.

**Comment by masoudganji** [comment]
Thanks GOD
I found the solution:
sudo apt-get install unixodbc-dev
after that everything is ok!
