### ISSUE TITLE
Question how to use Bind in odbc?

### ISSUE THREAD

**Issue by sefirosweb** [DeBoerTool/laravel-odbc-driver#13]
Hello, I'm using your plugin for odbc,

I'm using laravel 8 with ODBC

I'm tryng to bind variables on raw query and they returns errors
![image](https://user-images.githubusercontent.com/20754836/117262088-2ddd6480-ae51-11eb-86c6-be582aeef36c.png)

```php
        $result = DB::connection('vertica')->select(DB::raw("
        SELECT * FROM DM.sales LIMIT 9
        "), array('limit' => $limit));  // <-- here is the problem, i can't use bind for this odbc
        return $result;
```

**Comment by danielsdeboer** [comment]
Your raw expression isn't set up properly. Have a look here for how to use parameters in an Expression: https://fideloper.com/laravel-raw-queries
