### ISSUE TITLE
Installing odbc in Debian

### ISSUE THREAD

**Issue by Delvin-MCS** [DeBoerTool/laravel-odbc-driver#23]
In development, i am using windows 10 and with AccessDatabaseEngine.exe this package is working fine.
But in production (Debian 10), it shows error "Could not find driver". 
Been trying to install odbc driver from these article:
1. https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16
2. https://packages.debian.org/source/buster/mdbtools

**Comment by stanevvv** [comment]
Hello, I am facing the same issue on our production environment as well. By any chance, were you able to resolve the issue?

**Comment by Delvin-MCS** [comment]
Hello, 
At last, i didn't use the package on debian. 
And my database server is on Windows, so i installing laravel and get the data using api.
