### ISSUE TITLE
-104 Token unknown - line 1, char 15 "TABLENAME"

### ISSUE THREAD

**Issue by rtfmfm** [DeBoerTool/laravel-odbc-driver#24]
Hello,
when I try to select all the records from a table named TABLENAME, I'm getting the below error
```
Dynamic SQL Error SQL error code = -104 Token unknown - line 1, char 15 "TABLENAME" (SQLExecute[0] at ./ext/pdo_odbc/odbc_stmt.c:254)
```

Obviously, the generated query is `select * from "TABLENAME"` and the problem are the `"`  characters surrounding the name of the table.

I'm using a trial version of Devart ODBC driver for InterBase with Laravel 9.19 and PHP 8.1. 

Any idea what causes this error?
Thank you in advance!

**Comment by danielsdeboer** [comment]
No idea, sounds like that SQL grammar is different from the one that Laravel uses out the box.
