### ISSUE TITLE
Randomly getting "PDOException: SQLSTATE[IM002] SQLConnect: 0 [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified" error

### ISSUE THREAD

**Issue by fl4kez** [DeBoerTool/laravel-odbc-driver#31]
I'm working on a project with Angular for the frontend and laravel as backend. I need an Oracle connection so I setup a ODBC connection with 19_20 instantclient. That is the connection im using with this package.
My frontend requests some data every 10 seconds and sometimes and maybe even often, the request fails because the backend gives me this error:

`PDOException: SQLSTATE[IM002] SQLConnect: 0 [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified in file D:\git\PROJECT_XYZ\backend\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php on line 65
`
While having this Connection
![image](https://github.com/DeBoerTool/odbc-driver/assets/37409166/08987eaa-575f-4cea-b41e-ed03e6a2ce03)
![image](https://github.com/DeBoerTool/odbc-driver/assets/37409166/608dac6e-9835-4ea0-8e79-cdb988d93b59)

**Comment by danielsdeboer** [comment]
No idea. Doesn't sound like a problem with this package but a problem with your ODBC connection.
