### ISSUE TITLE
Add support for PHP 8.3.*

### ISSUE THREAD

**Issue by bergmab** [DeBoerTool/laravel-odbc-driver#35]
Can you make the project compatible with PHP 8.3.*?

_**Your requirements could not be resolved to an installable set of packages. 
 
   Problem 1
     - Root composer.json requires dbt/odbc-driver ^4 -> satisfiable by dbt/odbc-driver[4.0.0].
     - dbt/odbc-driver 4.0.0 requires php 8.1.*|8.2.* -> your php version (8.3.4) does not satisfy that requirement.
 
 Failed to update packages for  ./composer.json.**_

Thanks!

**Comment by danielsdeboer** [comment]
https://github.com/DeBoerTool/odbc-driver/releases/tag/4.0.1
