### ISSUE TITLE
PHP artisan serve works perfectly the database connects just fine, but when deploying on same server using nginx it fails

### ISSUE THREAD

**Issue by jeremiahsherrill** [DeBoerTool/laravel-odbc-driver#4]
Just curious if you have seen this before

SQLSTATE[60] SQLConnect: 0 [unixODBC][DataDirect][ODBC 20101 driver]1201

**Comment by jeremiahsherrill** [comment]
If for some reason anyone has this problem, the solution is to add the environment variable to .env

ODBCINI=/etc/odbc.ini  (or where ever your odbc.ini file is located.

**Comment by danielsdeboer** [comment]
I was going to say that if it works with `php artisan serve` but not nginx, it sounds like an nginx configuration issue... but I looks like you got there before I could :)
