### ISSUE TITLE
PDOException  : could not find driver

### ISSUE THREAD

**Issue by amalbabyconfianz** [DeBoerTool/laravel-odbc-driver#5]
The following is my ODBC config
[my-connector]
Description           = MySQL connection to  database
Driver                = MySQL ODBC 8.0 Driver
Database              = *****
Server                = localhost
User                  = root
Password              = *****
Port                  = 3306
Socket                = /var/run/mysqld/mysqld.sock

What is "odbc:DB_CONNECTION_STRING"?, is it in the above config?

**Comment by danielsdeboer** [comment]
Make sure you have the `pdo_odbc` extension enabled.

The `dsn` or `data source name` is whatever string your ODBC connection needs to connect. These vary by database vendor. Some examples here: https://github.com/DeBoerTool/odbc-driver#connection-string
