### ISSUE TITLE
: Call to undefined method Dbt\Odbc\Connection::getDoctrineDriver

### ISSUE THREAD

**Issue by jiejia** [DeBoerTool/laravel-odbc-driver#7]
php artisan admin:make PzmlController --model=App\Entities\Pzml

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Dbt\Odbc\Connection::getDoctrineDriver()

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:892

**Comment by danielsdeboer** [comment]
Because ODBC connections can have a variety of grammars, this package doesn't support DBAL operations.
