### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by jdavidbakr** [DeBoerTool/laravel-odbc-driver#8]
Just putting an issue in to get Laravel 7 support

**Comment by jdavidbakr** [comment]
https://github.com/DeBoerTool/odbc-driver/pull/9

**Comment by jdavidbakr** [comment]
I'm not sure if there are any changes in Laravel 7 that might break this package, my PR just has the version updated

**Comment by danielsdeboer** [comment]
I tested it against an L7 build and it works just fine!
